async () => {
  const data = [
    {
      linkId: '2',
      userId: '3',
      tgId: 5505218991,
      registrationDate: '2023-08-02T14:29:52.911Z',
      state: 'normal',
      lng: 'ru',
      phone: null,
      type: 'fl',
      sceneData: {},
      banned: false,
      top: false,
      checked: false,
      verified: false,
      inactive: false,
      balance: null,
      firstName: 'Slava',
      lastName: 'Kaderkin',
      username: undefined,
      href: 'https://t.me/@id5505218991',
      bio: 'Any bots and apps for telegram',
      avatarUrl: 'https://api.telegram.org/file/bot5811673269:AAE7sdWiBFO32xNTzGrzUVwcFT_sXGX-a4Q/profile_photos/file_99.jpg',
      referalsCount: 0,
      startDate: -1,
      paused: false,
      disput: false,
      revoked: false,
    },
    {
      linkId: '1',
      userId: '2',
      tgId: 1795394319,
      registrationDate: '2023-08-02T14:25:32.708Z',
      state: 'normal',
      lng: 'ru',
      phone: null,
      type: 'fl',
      sceneData: {},
      banned: false,
      top: false,
      checked: false,
      verified: false,
      inactive: false,
      balance: null,
      firstName: 'Arslav',
      lastName: undefined,
      username: '@arslaverza',
      href: 'https://t.me/@id1795394319',
      bio: 'Мучу — @affnet_bot. Ебу мозги — @brainfuck_er.',
      avatarUrl: 'https://api.telegram.org/file/bot5811673269:AAE7sdWiBFO32xNTzGrzUVwcFT_sXGX-a4Q/profile_photos/file_100.jpg',
      referalsCount: 1,
      startDate: -1,
      paused: false,
      disput: false,
      revoked: false,
    },
  ];

  return data;
}